volumes:
  architecture_rabbitmq:
networks:
  architecture:
    external: true

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.7-management-alpine
    volumes:
      - architecture_rabbitmq:/var/lib/rabbitmq
    networks:
      - architecture
    ports:
      - "15672:15672"
      - "5672:5672"
